project_id = "kyprnvazjyilthdzhqxh"

[functions.webhook]
verify_jwt = false

[functions.validate-promo-code]
verify_jwt = false

[functions.use-promo-code-and-book]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.attendance-nudge]
verify_jwt = false

[functions.cron-cancel-unpaid]
verify_jwt = false

[functions.process-referral-reward]
verify_jwt = false